### ISSUE TITLE
RootValue equivalent in graphql-go

### ISSUE THREAD

**Issue by stanonyime** [graphql-go/graphql#102]
In the express-graphql implementation there is an example of how to pass addition variables to the resolve function in the rootValue key. Example:
```javascript
app.use('/graphql', graphqlHTTP(request => ({
  schema: MySessionAwareGraphQLSchema,
  rootValue: { session: request.session },
  graphiql: true
})));
```
The session value is then accessed in the resolve function of a schema type:
```javascript
new GraphQLObjectType({
  name: 'MyType',
  fields: {
    myField: {
      type: GraphQLString,
      resolve(parentValue, _, { rootValue: { session } }) {
        // use `session` here
      }
    }
  }
});
```
Is there any documentation/example on how to pass and access root values from resolve functions in graphql go?

**Comment by bsr203** [comment]
as in this comment, you can use `Info.RootValue` https://github.com/graphql-go/graphql/pull/25#issuecomment-149684279

or `Context` is passed in directly now, which is intended for that. see the commit and example 
https://github.com/graphql-go/graphql/pull/98
https://github.com/graphql-go/graphql/commit/312dbef9053e42d634c69869efd26f28af1861da

**Comment by chris-ramon** [comment]
Hi @stanonyime, as mentioned by @bsr203 you have the two recommended options to obtain values within resolve function.

1. `Info.RootValue` - [eg](https://github.com/graphql-go/graphql/pull/25#issuecomment-149684279)
2. `Context` - [eg](https://github.com/graphql-go/graphql/blob/master/examples/context/main.go#L36)

Cheers!

**Comment by stanonyime** [comment]
@chris-ramon @bsr203 Thanks
