### ISSUE TITLE
Allow empty resolvers

### ISSUE THREAD

**Issue by F21** [graphql-go/graphql#111]
I have a schema with nesting that looks like this:
```go
queryType := graphql.NewObject(graphql.ObjectConfig{
		Name: "Query",
		Fields: graphql.Fields{
			"resources": &graphql.Field{
				Type: resourcesType,
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					return struct{}{}, nil // <- this is required for the query to work, even though it serves no purpose
				},
			},
		},
	})

resourcesType = graphql.NewObject(graphql.ObjectConfig{
		Name:        "Resources",
		Description: "Resource utilization information.",
		Fields: graphql.Fields{
			"memory": &graphql.Field{
				Type:        resourceType,
				Description: "Memory utilization information.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					memory, err := model.GetMemory()

					if err != nil {

						return nil, err
					}

					return memory, nil
				},
			},
		},
	})

resourceType = graphql.NewObject(graphql.ObjectConfig{
		Name:        "Resource",
		Description: "Resource utilization information for a type.",
		Fields: graphql.Fields{
			"total": &graphql.Field{
				Type:        graphql.Float,
				Description: "The total available.",
			},
			"used": &graphql.Field{
				Type:        graphql.Float,
				Description: "The amount used.",
			},
		},
	})
```

A query would look like this:

```graphql
query test {
          resources {
            memory{
              total
              used
            }
          }
        }
```

If I don't have a `resolve` at the root object of the `Resources` type, the query wouldn't work:

```
{
  "data": {
    "resources": null
  }
}
```

I think it would be useful if a field that does not have a resolver is allowed to go "deeper", so that the child resolvers can resolve.

**Comment by CentaurWarchief** [comment]
Hey @F21, I never tested it, but it could be done with the current graphql-js implementation? That would be such an interesting feature. A friend of mine ran into the same issue some weeks ago, we had to define the resolve in the parent even without needing all fields, for example:

```
{
  memory {
    virtual {
      total
      used
      available
    }
  }
}
```

In `memory` we have both `virtual` and `swap`, but we needed to resolve both virtual and swap which leads to performance-related issues. 

/cc @txgruppi

**Comment by F21** [comment]
@CentaurWarchief I haven't really had a chance to play with the `graphql-js` version (only went through the relay tutorial). However, I think the javascript implementation also has this limitation: https://github.com/graphql/graphql-js/issues/154

**Comment by txgruppi** [comment]
Our solution was to create a type for `memory` and use it in the resolve function.

```go
func NewMemoryData() *MemoryData {
	return &MemoryData{}
}

type MemoryData struct {
	Swap    *SwapData    `json:"swap"`
	Virtual *VirtualData `json:"virtual"`
}
```

```go
Resolve: func(p graphql.ResolveParams) (interface{}, error) {
 	return NewMemoryData(), nil
},
```

**Comment by sogko** [comment]
This is kinda tricky, because the way the `executor` works is by evaluating the query top-down.
As part of its pruning process, it would only look at the child if the parent node has something to evaluate.

> I think it would be useful if a field that does not have a resolver is allowed to go "deeper", so that the child resolvers can resolve.

Every field actually has a default resolver, which you override by specifying it in the schema you defined.

So if the resolver (regardless if it's default or user-specified) returns a `nil` value, the `executor` won't try to see if its child fields has a value.

It is possible to design the `executor` to try evaluate all child fields even when the parent field evaluates to `nil`, but that could possibly lead to evaluating every field in the schema for every query.

Having the value of `resources` field to be nil but its own fields to have values are kinda counter-intuitive.

@F21  solution of returning an empty anonymous struct at first glance seems hacky but is perfectly valid.

Can I suggest an alternate solution (which is practically the same as the one posted above), but probably more natural way of writing the schema.

```go
type Memory struct {
	Total float64 `json:"total"`
	Used float64 `json:"used"`
}

type Resources struct {
	Memory Memory `json:"memory"`
}

func (resources *Resources) GetMemory() *Memory {
	// resource-heavy operation to fetch stats
	return &Memory {
		Total: 1024,
		Used: 100,
	}
}

func main() {
	resourceType := graphql.NewObject(graphql.ObjectConfig{
		Name:        "Resource",
		Description: "Resource utilization information for a type.",
		Fields: graphql.Fields{
			"total": &graphql.Field{
				Type:        graphql.Float,
				Description: "The total available.",
			},
			"used": &graphql.Field{
				Type:        graphql.Float,
				Description: "The amount used.",
			},
		},
	})

	resourcesType := graphql.NewObject(graphql.ObjectConfig{
		Name:        "Resources",
		Description: "Resource utilization information.",
		Fields: graphql.Fields{
			"memory": &graphql.Field{
				Type:        resourceType,
				Description: "Memory utilization information.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					if resources, ok := p.Source.(*Resources); ok {
						return resources.GetMemory(), nil
					}
					return nil, nil
				},
			},
		},
	})
	queryType := graphql.NewObject(graphql.ObjectConfig{
		Name: "Query",
		Fields: graphql.Fields{
			"resources": &graphql.Field{
				Type: resourcesType,
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					return &Resources{}, nil
				},
			},
		},
	})
	...
}
```

**Comment by F21** [comment]
@sogko Thanks for posting the sample code. That really helped!

I think your solution is exactly what I am looking for! :smile:

**Comment by bbuck** [comment]
@sogko Not sure if you meant to do something else but, this bit:

```go
log.Printf(car.Year) 
```

Panics because `car.Year` is an `int` while `log.Printf`expects a `string`. If you change to `Println` or give it a format string. Again, you may have meant something else but I just wanted to point that out.

**Comment by sogko** [comment]
@bbuck hahaha yeah thanks for pointing that out, it should be `log.Println()`, I just meant to give an example of getting a value of a field from a nil struct, thanks! 👍🏻
