### ISSUE TITLE
Error Handling?

### ISSUE THREAD

**Issue by pyros2097** [graphql-go/graphql#115]
Graphql go right now swallows all errors and returns them back to the user. Sometimes we get database errors like `SQL State: conflicting foreign key` and this error goes back to the user. This is related to https://github.com/graphql/graphql-js/issues/28.

 We should add some add some ErrorHandling logic to prevent some of these errors for going back and also returning them back to the application so that it can know what to do with it (like log, mail).

The graphql scala https://github.com/sangria-graphql/sangria version have done a really good way of handling it here http://sangria-graphql.org/learn/ Maybe we should try their approach?

**Comment by bbuck** [comment]
Is this not already possible with the current state of the library? I'm not sure if this feature existed at the time this issue was posted but as it stands a resolve function now has a return type of `(interface{}, error)` letting you receive and process any errors you have.

Should this issue be closed?

**Comment by bsr203** [comment]
I am bit worried about not much activities on pending pull requests and issues. @chris-ramon and @sogko poured ton of effort initially and wonder how they feel about the project now. May be it is a good idea to include @bbuck @pyros2097 and other frequent users of this library to have commit rights?

**Comment by pyros2097** [comment]
Actually even I've stopped using this library and gone back to using graphql-js and the other go-graphql library and am in the process of creating one for rust(just for fun).
Btw this issue should be closed since I made the pull request long ago and fixed the error handling issue.

**Comment by zonr** [comment]
Storing `gqlerrors.Error` in `graphql.Result.Errors` will provide structured and more complete error context to the library users and therefore makes custom exception handing easier. graphql/graphql-js has made the transition in graphql/graphql-js#118. Should we follow their changes?
