### ISSUE TITLE
introspection query from graphql-js v0.5.0 fails

### ISSUE THREAD

**Issue by sfriedel** [graphql-go/graphql#126]
When trying to use graphql-go from graphql-js v0.5.0 the introspection query fails:

```
errors=[map[message:Cannot query field "locations" on "__Directive". locations:[{13 9}]]] 
```

The cause of this is the [april 2016 update to the GraphQL Spec](https://github.com/facebook/graphql/releases/tag/April2016) which introduced some breaking changes related to introspection.

Are there already plans to update the library for the latest spec changes? Also, is it documented somewhere to which version of the GraphQL spec graphql-go currently complies to?

**Comment by sogko** [comment]
Hi @sfriedel!

We already have a PR #117 which brings this library on par with `graphql-js v0.4.18` and compliant with most of April 2016 spec. It's currently pending review and will be merged to the master branch soon.
(Currently the master branch is close to `graphql-js v0.4.3 `)

There is also another PR #123 that I'm working on, which aims to bring parity to `v0.5.0` and will be finally fully compliant with April 2016 spec. (Just need to find time outside of normal work ;) )

Regarding documenting which spec `graphql-go` complies to: We have recently discussed that we will start to tag our releases and documenting with part  of the spec it has implemented. We will start doing that with `v0.4.18` / #117 

Cheers!

**Comment by sfriedel** [comment]
Hi @sogko,

that's really good news. I guess I was just getting a bit concerned about the lack of activity in the repo.

Thank you and all the other contributors for your time and work.
