### ISSUE TITLE
why use Float32 for GraphQLFloat?

### ISSUE THREAD

**Issue by teloon** [graphql-go/graphql#130]
There surely will be cases that need better precision or number range. Just want to know if there's any concern not using Float64 here.

**Comment by sogko** [comment]
Actually this is valid, there is no reason why it should be Float32. 

From [spec](http://facebook.github.io/graphql/#sec-Float):
> The Float scalar type represents signed double‐precision fractional values as specified by [IEEE 754](https://en.wikipedia.org/wiki/IEEE_floating_point). Response formats that support an appropriate double‐precision number type should use that type to represent this scalar.

It only specifies that it has to be IEEE 754, nothing about 32 vs 64-bit.

**Comment by teloon** [comment]
diff looks good. thanks for your effort!

**Comment by sogko** [comment]
Merged related PR #133.

Thanks @teloon! 

Cheers!
