### ISSUE TITLE
wrong execution order of multiple mutations in one request

### ISSUE THREAD

**Issue by sfriedel** [graphql-go/graphql#145]
The GraphQL spec states that mutations should be executed serially and in the order that they were specified.

Currently this isn't the case in graphql-go. Mutations are executed in random order (I'd guess they are stored in a map somewhere because order changes with every restart).

> When evaluating a grouped field set serially, the executor must consider each entry from the grouped field set in the order provided in the grouped field set. It must determine the corresponding entry in the result map for each item to completion before it continues on to the next item in the grouped field set:

https://facebook.github.io/graphql/#sec-Serial-execution

**Comment by robermorales** [comment]
Something new about this?

**Comment by djmcgreal** [comment]
The problem is in `executeFields(Serially)`, `p.Fields` is a map created by `collectFields`. Since Go iterates over maps in an arbitrary order, this isn't an approach that can be compatible with the spec.
