### ISSUE TITLE
Question: printing the schema

### ISSUE THREAD

**Issue by rantav** [graphql-go/graphql#146]
In this file I see examples how to print a schema given an `ast`. https://github.com/graphql-go/graphql/blob/master/language/printer/schema_printer_test.go

However, if I define the schema in Go, such as in the example on the readme page, how do I go about printing it then? 

```
package main

import (
    "encoding/json"
    "fmt"
    "log"

    "github.com/graphql-go/graphql"
    "github.com/graphql-go/graphql/language/printer"
)

func main() {
    // Schema
    fields := graphql.Fields{
        "hello": &graphql.Field{
            Type: graphql.String,
            Resolve: func(p graphql.ResolveParams) (interface{}, error) {
                return "world", nil
            },
        },
    }
    rootQuery := graphql.ObjectConfig{Name: "RootQuery", Fields: fields}
    schemaConfig := graphql.SchemaConfig{Query: graphql.NewObject(rootQuery)}
    schema, err := graphql.NewSchema(schemaConfig)

    // I wish I could do: 
    printer.Print(schema) // This is a compation error, Print expects an ast element. 
    // How does one print a schema that was defined in Go such as here? 

```

Thank you!

**Comment by bsr203** [comment]
I may be reading your intention wrongly, but if you want to output the schema as json to consume by graphql server / relay, this is the script I use

```
package main

import (
	"my/schema" // this is where I define my schema
	"encoding/json"
	"io/ioutil"
	"log"
	"os"

	"github.com/graphql-go/graphql"
	"github.com/graphql-go/graphql/testutil"
)

func main() {
	// Save JSON of full schema introspection for Babel Relay Plugin to use
	result := graphql.Do(graphql.Params{
		Schema:        schema.Schema,
		RequestString: testutil.IntrospectionQuery,
	})

	if result.HasErrors() {
		log.Fatalf("ERROR introspecting schema: %v", result.Errors)
		return
	} else {
		b, err := json.MarshalIndent(result, "", "  ")
		if err != nil {
			log.Fatalf("ERROR: %v", err)
		}
		err = ioutil.WriteFile("./schema.json", b, os.ModePerm)
		if err != nil {
			log.Fatalf("ERROR: %v", err)
		}

	}
}```

**Comment by rantav** [comment]
Thanks @bsr203 that's indeed a step in the right direction, although not exactly what I was looking for. 

Perhaps it isn't possible... but I'd love to have a way to print the schema in a _human readable way_, sort of translate the graphql.Schema object into a string of the sort of the kitchen-sink schema example https://github.com/graphql-go/graphql/blob/master/schema-kitchen-sink.graphql


BTW, my first steps in gql land so perhaps I'm not explaining myself right. I just realized "introspection" is a thing in gql http://graphql.org/docs/introspection/
But anyway, introspection results in machine-readable json response, I'd love to have human-readable scheme out of my `graphql.Schema` instance

**Comment by bsr203** [comment]
I never tried that. One possibility is to write a small node app, where the schema json file is loaded and output back to the shorthand notation using https://github.com/graphql/graphql-js/blob/master/src/utilities/schemaPrinter.js

I also don't know whether it already exists in this package as I never looked into it.

**Comment by rantav** [comment]
@bsr203 thanks again for replying. 
Eventually I did use https://github.com/graphql/graphql-js/blob/master/src/utilities/schemaPrinter.js in a different nodejs process to serve a human readable schema of my graphql interface. That's pretty nice, thanks for the link!

Here's nodejs code just for reference:

```
import { printSchema, buildClientSchema } from 'graphql';

function  getGraphqlSchema() {
    // Send the query to the server
    // invokeGql is a (fibered) function that sends an HTTP request to to the /graphql endpoint at the go web server 
    const introspectionSchema = invokeGql(introspectionQuery);
    const schema = buildClientSchema(introspectionSchema.data);
    return printSchema(schema);
}

// This is a copy of the inrospectionQuery from here https://github.com/graphql-go/graphql/blob/491504a5ac801fc9d72ecae4e57e5231c6a57595/testutil/introspection_query.go
// The nodejs introspectionQuery isn't compatible with the go implementation. 
const introspectionQuery = `
query IntrospectionQuery {
  __schema {
    queryType { name }
    mutationType { name }
    types {
      ...FullType
    }
    directives {
      name
      description
      args {
        ...InputValue
      }
      onOperation
      onFragment
      onField
    }
  }
}

fragment FullType on __Type {
  kind
  name
  description
  fields {
    name
    description
    args {
      ...InputValue
    }
    type {
      ...TypeRef
    }
    isDeprecated
    deprecationReason
  }
  inputFields {
    ...InputValue
  }
  interfaces {
    ...TypeRef
  }
  enumValues {
    name
    description
    isDeprecated
    deprecationReason
  }
  possibleTypes {
    ...TypeRef
  }
}

fragment InputValue on __InputValue {
  name
  description
  type { ...TypeRef }
  defaultValue
}

fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
      }
    }
  }
}`;
```

**Comment by bsr203** [comment]
Hi, I needed this just now, and found `graphql-js` introspectionQuery works fine. I saw the comment in your code that it doesn't. here is my code.

```
import { printSchema, buildClientSchema, introspectionQuery } from 'graphql';
import axios from 'axios';

const PORT = 8080;

const headers = {
  'Content-Type': 'application/json',
};

axios({
  url: 'http://localhost:' + PORT + '/graphql',
  method: 'post',
  headers,
  data: {operationName: "IntrospectionQuery", query: introspectionQuery, variables: ''},
}).then(({data}) => {
  const schema = buildClientSchema(data.data);
  console.log(printSchema(schema));
}).catch(e => console.log(e));

```

**Comment by cguadir** [comment]
> Hi, I needed this just now, and found `graphql-js` introspectionQuery works fine. I saw the comment in your code that it doesn't. here is my code.
> 
> ```
> import { printSchema, buildClientSchema, introspectionQuery } from 'graphql';
> import axios from 'axios';
> 
> const PORT = 8080;
> 
> const headers = {
>   'Content-Type': 'application/json',
> };
> 
> axios({
>   url: 'http://localhost:' + PORT + '/graphql',
>   method: 'post',
>   headers,
>   data: {operationName: "IntrospectionQuery", query: introspectionQuery, variables: ''},
> }).then(({data}) => {
>   const schema = buildClientSchema(data.data);
>   console.log(printSchema(schema));
> }).catch(e => console.log(e));
> ```

This worked for thanks for that

**Comment by kukwuka** [comment]
how can i print schema in go not in js?
