### ISSUE TITLE
Link godocs in readme

### ISSUE THREAD

**Issue by kyteague** [graphql-go/graphql#160]
Almost impossible to find documentation for the API.  Even difficult to google.

Please link https://godoc.org/github.com/graphql-go/graphql to README.

**Comment by kyteague** [comment]
Requiring people to memorize a magic url to reach your documentation doesn't sound like a good solution.  Every project links its documentation.

**Comment by chris-ramon** [comment]
Hi @kyteague, thanks letting us know about the lack of docs, its something that def. should be improve asap, and actually we do have a link to `godoc` within the README:
  ![godocgql 2](https://cloud.githubusercontent.com/assets/1000404/18652280/b7e89e8c-7e96-11e6-89ed-9ac7a3baa144.png)

**Comment by kyteague** [comment]
Thanks @chris-ramon 

I didn't notice as I never look at the badges.  I always `ctrl+f` and look for "doc" in the text.

**Comment by bbuck** [comment]
@kyteague I'm not an owner of a project, or suggesting you remember a magic URL. I'm simply pointing out, for future reference, how you can access the documentation of _any Go project that is open source_ from here on out in case you can't find a link or find the docs in Google. Just trying to help you out.
