### ISSUE TITLE
Circular references causes compiler error

### ISSUE THREAD

**Issue by rubberviscous** [graphql-go/graphql#164]
When defining GraphQL types where two types reference each other, this causes compiler error when building:

`typechecking loop involving showType = graphql.NewObject(graphql.ObjectConfig literal)`

Here's the GraphQL types that I have defined where it references each other:

`var showType = graphql.NewObject(
    graphql.ObjectConfig{
        Name: "Show",
        Fields: graphql.Fields{
            "id": &graphql.Field{
                Type: graphql.String,
            },
            "episodes": &graphql.Field{
                Type: graphql.NewList(episodeType),
            }
        }
    }
)`

`var episodeType = graphql.NewObject(
    graphql.ObjectConfig{
        Name: "Episode",
        Fields: graphql.Fields{
            "id": &graphql.Field{
                Type: graphql.String,
            },
            "show": &graphql.Field{
                Type: showType,
        }
    }
)`

Are there any workarounds for this issue?

**Comment by sfriedel** [comment]
@rubberviscous I also had this problem once. My solution was dynamically adding one of the problematic fields inside `init()`, It's not really pretty but it seems work at least

```go
package main

import (
	"github.com/graphql-go/graphql"
)

var showType = graphql.NewObject(graphql.ObjectConfig{
	Name: "Show",
	Fields: graphql.Fields{
		"id":       &graphql.Field{Type: graphql.String},
		"episodes": &graphql.Field{Type: graphql.NewList(episodeType)},
	},
})

var episodeType = graphql.NewObject(graphql.ObjectConfig{
	Name: "Episode",
	Fields: graphql.Fields{
		"id": &graphql.Field{Type: graphql.String},
	},
})

func init() {
	episodeType.AddFieldConfig("show", &graphql.Field{Type: showType})
}
```

**Comment by rubberviscous** [comment]
@sfriedel That worked! Many thanks!

**Comment by mastertinner** [comment]
In JavaScript this problem has already been solved. There, the `Fields` property can either be a hashmap of fields or a function which returns a hashmap of fields. Since Go doesn't allow that, I would suggest to add a new property `DynamicFields` which is must be of type `func () graphql.Fields`. `graphql.NewObject()` would then combine `Fields` and what's returned by `DynamicFields`.

**Comment by chris-ramon** [comment]
Hi @rubberviscous, thanks a lot for reaching us for a question, also the solution @sfriedel wrote above is the go-to one, closing this one, thanks guys!
