### ISSUE TITLE
Update precision for float64 parsing in graphql.Float

### ISSUE THREAD

**Issue by matheusmartin** [graphql-go/graphql#165]
The current parsing of float values uses 32 precision which cause the resulting float variable from `graphql.ResolveParams` to have a dirty floating point, e.g., 32.45 would become 32.45000230230230.

I changes line 134 from

`if floatValue, err := strconv.ParseFloat(valueAST.Value, 32); err == nil {`

to

`if floatValue, err := strconv.ParseFloat(valueAST.Value, 64); err == nil {`

and it solved the problem.

**Comment by bbuck** [comment]
Did the library only parse as 32 bit? The GraphQL spec specifies that floats should be handled as double precision. If there are more instances where floats are treated as `float32` instead of `float64` they should be changed.
