### ISSUE TITLE
I think this module is too strict.

### ISSUE THREAD

**Issue by riverleo** [graphql-go/graphql#166]
I tried to use this module for my project thru production.
But I can't understand why I have to write schema so strictly like this.
It would be way easier if just give us data which parsed graphql.
For now, it's way harder to apply graphql to our production.

If you have a chance to develop this module, please make a graphql's parser first.

**Comment by bbuck** [comment]
The point of GraphQL is to be a strict definition of what your service can return. It's not meant to be loose, and this is not the GraphQL source this is just a conversion to Go. Facebook defines the standards for any GraphQL compliant system [here](http://graphql.org/).

Not all systems need or should have a GraphQL backend, so if you can't make it work for your production system that might be telling that you don't need it. REST is still better suited for dynamic content (in other words, you don't have a strict structure) and should be used over GraphQL in those cases. GraphQL is specific to a predefined strict data model that can ideally be easily interacted with/viewed like a graph.
