### ISSUE TITLE
Enum Argument

### ISSUE THREAD

**Issue by ajackson-cpi** [graphql-go/graphql#169]
Where can I find an example of an enum argument?
I have the need for a list of enum as an argument (for an "Order By" usage).

**Comment by narqo** [comment]
You might check the tests to see a basic example https://github.com/graphql-go/graphql/blob/8c317402d1b72dff3dd9008bad7e41d0ae96e3c6/testutil/testutil.go#L281-L293

**Comment by ajackson-cpi** [comment]
I see no argument with a list of enum. I'm getting a failure using:
```
orderByChoices := graphql.EnumValueConfigMap{
   "EffectiveDateMax": &graphql.EnumValueConfig{Value: "EffectiveDateMax"},
   "EffectiveDateMin": &graphql.EnumValueConfig{Value: "EffectiveDateMin"},
   .... more omitted for brevity...
}

orderArg := graphql.FieldConfigArgument{
  "First": &graphql.ArgumentConfig{
			Type:        graphql.NewList(NewEnum(graphql.EnumConfig{Name: "OrderBy", Values: orderByChoices})),
			Description: "Ordered results so previous element meets this condition.",
		}
}
```
--------
When used, I get:
Argument "First" has invalid value ["EffectiveDateMax"].
In element #1: Expected type "OrderBy", found "EffectiveDateMax".

**Comment by bbuck** [comment]
I'm looking at https://github.com/graphql-go/graphql/blob/master/enum_type_test.go#L164 and see that maybe you're query is where the error is (which you didn't show), maybe `First: [EffectiveDateMax]` is what you're looking for instead of `First: ["EffictiveDateMax"]` in the GraphQL query?

**Comment by ajackson-cpi** [comment]
Thanks, I've found the combo I hadn't tried before:
- Enum values in a query are NOT quoted:    {Blog(OrderBy: [EffectiveDateMax]){Subject}}
AND
- EnumConfig.Name must be set and unique.   

It fails if either of these is missed.
