### ISSUE TITLE
GraphQL spec version.

### ISSUE THREAD

**Issue by xzyfer** [graphql-go/graphql#175]
It would be good to have some indication of what version of the GraphQL spec this implementation is currently aligned with. The current version is [graphql-js@v0.8.2][1].

A [release][2] was tagged some time ago which was aligned with [graphql-js@v0.4.18][3]. That release is currently 46 commits behind master, and there is currently no indication of what graphql-js version master is currently aligned with.

[1]: https://github.com/graphql/graphql-js/releases/tag/v0.8.2
[2]: https://github.com/graphql-go/graphql/releases/tag/v0.4.18
[3]: https://github.com/graphql/graphql-js/releases/tag/v0.4.13

**Comment by paulosuzart** [comment]
Yes, I'm a bit confused. I see in the README that this lib is compatible with 

> however future efforts will be guided directly by the latest formal GraphQL specification (currently: October 2015).

But the comment above mentions [graphql-js@v0.8.2](https://github.com/graphql/graphql-js/releases/tag/v0.8.2). So what is the real GrpahQL spec draft this lib support? Any one can share this?

Thanks

**Comment by christianpv** [comment]
Short answer: I believe its fully compatible with the [April 2016](https://github.com/facebook/graphql/releases/tag/April2016) spec. 

@sogko ported changes from [graphql-js@v0.6.0](https://github.com/graphql/graphql-js/releases/tag/v0.6.0) which is now in master. The previous version which was [v0.5.0](https://github.com/graphql/graphql-js/releases/tag/v0.5.0) was implementing graphql [April 2016](https://github.com/facebook/graphql/releases/tag/April2016) spec.

**Comment by paulosuzart** [comment]
Thanks Christian. The last graphql draft is from October 2016. This lib is
possibly behind. Any plans to cope with latest spec? Any specific
contribution needed?

**Comment by christianpv** [comment]
@paulosuzart I believe the GraphQL April 2017 spec might be release this month so this implementation will be two versions behind. The core developers of this implementation can't dedicate that much time anymore. There is an issue to find out how to address the continued development of this implementation: https://github.com/graphql-go/graphql/issues/196

If you would like to collaborate, please post your comments on that issue.
