### ISSUE TITLE
Getting runtime Error if a custom scalar type getting called at runtime through interface resolve method only.

### ISSUE THREAD

**Issue by robinskumar73** [graphql-go/graphql#194]
Thanks for creating this beautiful piece of software. 
I have created 2 custom scalar type `Admin` and `Customer` schema and both my schema implements a `UserInterface'. Now in my root query, I have defined a field `getUser` which has the type of `UserInterface` which on runtime resolve to either `Admin` or `Customer` type.

Whenever I run this I am getting this error 

```
{
  "data": {
    "getUser": null
  },
  "errors": [
    {
      "message": "Runtime Object type \"Admin\" is not a possible type for \"UserInterface\".",
      "locations": []
    }
  ]
}
```

Now if I defined another field in my root query something like `getAdmin` with type `Admin` and  `getCustomer` with type `Customer` then `getUser` method is working.

**Comment by robinskumar73** [comment]
I figured it out. 
I will have to declare I will have to declare explicity `Types` in schema.


```
TestSchema, _ = graphql.NewSchema(graphql.SchemaConfig{
		Query: queryType,
		Types: []graphql.Type{adminType,  customerType},
})
```

**Comment by bbuck** [comment]
I'm glad you were able to resolve this yourself!
