### ISSUE TITLE
Can we get a release?

### ISSUE THREAD

**Issue by zbintliff** [graphql-go/graphql#204]
Some good merges have happened since 0.6.0. Any chance this is ready for a release any time soon?

**Comment by christianpv** [comment]
@chris-ramon did release new versions. Latest is [v0.7.2](https://github.com/graphql-go/graphql/releases/tag/v0.7.2). We can close this issue.

**Comment by zbintliff** [comment]
Yup I'll close! we even updated to 0.7.2 thanks!

**Comment by chris-ramon** [comment]
thanks a guys! — also create a new release [v0.7.3](https://github.com/graphql-go/graphql/releases/tag/v0.7.3) with latest improvements.
