### ISSUE TITLE
replace x/net/context with context package

### ISSUE THREAD

**Issue by mbertschler** [graphql-go/graphql#212]
Thanks for this great library, I really like to use it!
At some point this library should use the `context` standard library package instead of the old `golang.org/x/net/context` one. The new package was introduced in Go 1.7, and is now available for almost a year already.

This is a little problem for me since I use the standard context package in my code, and the old x/net package then causes import conflicts, which requires me to change the import to something like netcontext so that I can use both at the same time.

If you decide that this is something we should do, then I could send a PR that changes this.

**Comment by bbuck** [comment]
Make a PR for it!

**Comment by chris-ramon** [comment]
closed via: https://github.com/graphql-go/graphql/pull/214 thx a lot!
