### ISSUE TITLE
Is there a way to generate the post query in go?

### ISSUE THREAD

**Issue by beatscode** [graphql-go/graphql#222]
I've been looking to use Gopherjs to write my frontend logic. For a project I plan to use graph-ql. Curious if there is any way to create the graph-ql post string in go? Work around to be to use a 3rd party client but doesn't hurt to ask.

**Comment by chris-ramon** [comment]
Hi @beatscode, thanks for reaching us for a question.

Could you expand on:
```

**Comment by beatscode** [comment]
For instance in the http example

on https://github.com/graphql-go/graphql/blob/master/examples/http/main.go#L96 there is a curl string with a query get parameter. I'd like to know if there is a way to generate this query parameter in just go. I'm guessing this query string is assumed to be generated from a javascript graph-ql client.

```
http.HandleFunc("/graphql", func(w http.ResponseWriter, r *http.Request) {
		result := executeQuery(r.URL.Query().Get("query"), schema)
		json.NewEncoder(w).Encode(result)
	})

	fmt.Println("Now server is running on port 8080")
	fmt.Println("Test with Get      : curl -g 'http://localhost:8080/graphql?query={user(id:\"1\"){name}}'")
	http.ListenAndServe(":8080", nil)
```

**Comment by beatscode** [comment]
My fault, I thought there was some special format to the query string
