### ISSUE TITLE
typechecking loop error with circular node reference

### ISSUE THREAD

**Issue by tobyjsullivan** [graphql-go/graphql#258]
I'm hitting a wall while trying to build an API with circular references between types.

A simplified example of my types looks like this:
```
Role {
  Company
  Employee
}
Employee {
  roles List(Role)
}
```

Attempting to create this results in a `typechecking loop` error from the go compiler.

This seems to be a result of the `employeeType` referencing `roleType` which in turn references `employeeType` again.

I would expect these kinds of models to be central to a Graph API. Is there a better way to be building this?

Thanks for any feedback.

**Comment by jmalloc** [comment]
Looks like "field thunks" are the way to do this.  The `graphql.ObjectConfig.Fields` field can be a function which is evaluated lazily, rather than a `map[string]Field`. 

Using field thunks along with moving the definition into an `init()` function seems to do the trick.

```go
var SomeType graphql.Type

func init() {
	SomeType = graphql.NewObject(graphql.ObjectConfig{
		Name: "SomeType",
		Fields: func() graphql.Fields { // notice func here
			return graphql.Fields{
				"circularRef": {
					Type: Environment,
				},
			}
		},
	})
}
```

**Comment by jmalloc** [comment]
Ok, the issue is because a type-switch is being used to identify whether a thunk is being used, and my closure was not statically typed as `FieldsThunk`, the correct example is:

```go
var SomeType graphql.Type

func init() {
	SomeType = graphql.NewObject(graphql.ObjectConfig{
		Name: "SomeType",
		Fields: graphql.FieldsThunk(func() graphql.Fields { // notice func here
			return graphql.Fields{
				"circularRef": {
					Type: Environment,
				},
			}
		}),
	})
}
```

**Comment by tobyjsullivan** [comment]
You're a lifesaver, mate! Thank you. Closing the issue as this solution resolved it.

**Comment by bbuck** [comment]
As a side note, another way to do this is with [`Object.addFieldConfig`](https://godoc.org/github.com/graphql-go/graphql#Object.AddFieldConfig) in the past. Creating partial types for each and then adding the circular fields afterwards.

**Comment by SasukeBo** [comment]
there is a problem with FieldThunk and AddFieldConfig, if your object's fields returned by FieldThunk, you can't dynamically add field into your object by AddFieldConfig. I ran into this problem because I restruct my project's fields/types/schema module.
