### ISSUE TITLE
[QUESTION] How can I pass custom value down through the tree?

### ISSUE THREAD

**Issue by universonic** [graphql-go/graphql#269]
Hello, I am implementing an app with GraphQL and OAuth 2.0. I noticed that since there is no way to pass custom value down through the queried object tree, is there a possible way to pass some my own variable such as `http.Request.URL`, or custom context that implemented by myself? I want to insert some policy filter functions inside the `Resolve` function, so I am able to check if a user has been authorized or if the user has the correct authorization before resolving the object result. I have tried to set the `Value` field of `params.Context` but it did not work.

**Comment by amkoehler** [comment]
It sounds like you're on the right track with `Context` but perhaps you aren't initializing it correctly. We use it to pass down header information:

```go
params := graphql.Params{
  Schema:         *schema,
  RequestString:  opts.Query,
  VariableValues: opts.Variables,
  OperationName:  opts.OperationName,
  Context: context.WithValue(context.Background(), "x-auth-id", "12345"),
}

graphql.Do(params)
```

and in any resolver function here's how to access that value:

```go
stringField := &graphql.Field{
  Type:        graphql.String,
  Description: "A GraphQL Field",
  Resolve: func(p graphql.ResolveParams) (interface{}, error) {
    headerValue := p.Context.Value("x-auth-id")

    ...
  }

```

Note: one of our go tools (gofmt, I think) strongly recommends not using a string for the key but a custom type struct instead.

**Comment by universonic** [comment]
It does work and quite helpful.
