### ISSUE TITLE
Add some documentation

### ISSUE THREAD

**Issue by manishrjain** [graphql-go/graphql#27]
Hi, I'm planning to use your implementation of GraphQL in Go. I couldn't find any convenient starting points to figure out how to play with this. Can you add some examples in your README? Or, via Golang test usages.

I have a MVP level execution engine ready to serve Graph data. So, if you want to collaborate in some way, that'll be great.

**Comment by thanhliem89dn** [comment]
Hi Manishrjain, 

You could take a look on my example https://github.com/thanhliem89dn/graphql-go/tree/master/examples/http. I port this from original graphql site http://graphql.org/docs/getting-started/ . So you can look deeper by follow official graphql site
Thanks

**Comment by sogko** [comment]
Hi guys

@manishrjain Thanks for taking your time to look into using this package for your project  👍🏻
Right now, this project is still in its infancy, and welcome more contribution from the community.
And documentation still needs a lot of work at the moment.

Like @thanhliem89dn mentioned, his example would be a great starting point (related PR #21)

Other great places to start:
- Tests files: for e.g. [graphql_test.go](https://github.com/chris-ramon/graphql-go/blob/master/graphql_test.go). Most of the public API have corresponding tests.
- Go examples in [awesome-graphql](https://github.com/chentsulin/awesome-graphql#example-go). Time to time, I try to add examples that uses `graphql-go` into the awesome list compiled by @chentsulin.
Currently, here are some examples:
  * [golang-relay-starter-kit](https://github.com/sogko/golang-relay-starter-kit) - Barebones starting point for a Relay application with Golang GraphQL server.
  * [golang-graphql-playground](https://github.com/sogko/golang-graphql-playground) - An example Golang GraphQL server written with graphql-go and graphql-relay-go. Try live demo at: http://bit.ly/try-graphql-go
  * [todomvc-relay-go](https://github.com/sogko/todomvc-relay-go) - Port of the React/Relay TodoMVC app, driven by a Golang GraphQL backend.

- I've written a couple of posts on getting started with golang + graphql using `graphql-go` (also listed on `awesome-graphql`
  * [Learn Golang + GraphQL + Relay, Part 1: Your first Golang GraphQL server](https://wehavefaces.net/learn-golang-graphql-relay-1-e59ea174a902)
  * [Learn Golang + GraphQL + Relay, Part 2: Your first Relay application](https://wehavefaces.net/learn-golang-graphql-relay-2-a56cbcc3e341)


I think moving on we can figure out:
- what examples we could provide to best grow and serve the community
- how we make it easier for users to start picking up `graphql-go` 

Hope this helps you @manishrjain 
Cheers!

**Comment by sogko** [comment]
With PR #21 and PR #52 merged, together with the various improvements in the README.md, we'll considered this issue as resolved. 

Feel free to re-open if you feel that your original concern has not been addressed.

Cheers!
