### ISSUE TITLE
High memory usage ( 500mb, 1gb! )

### ISSUE THREAD

**Issue by Kliton** [graphql-go/graphql#276]
I have a resolver that gets 10.000 records from the db and then return that in the query.

I have a massive use of ram when i call this query ( the object is very small in term of bytes ).

I will attach the complete pprof svg.

[pprof009.svg.zip](https://github.com/graphql-go/graphql/files/1689575/pprof009.svg.zip)

Here's the code:
```golang
var GetAllWorkersReport = &graphql.Field{

	Type:        graphql.NewList(WorkerReport),
	Description: "",
	Resolve: func(p graphql.ResolveParams) (interface{}, error) {

		start := time.Now()

		var res []*workers.WorkerReport
		stream, err := rpc.Workers().GetWorkersReport(context.Background(), &workers.None{})

		if err != nil {
			log.Println("[ERROR]", err.Error())
			return nil, err
		}

		for {

			rcv, err := stream.Recv()
			if err != nil {
				if err != io.EOF {
					return nil, err
				}
				break
			}

			// if len(res) < 200 {
			res = append(res, rcv)
			// }
		}

		util.TimeTrack(start, "Stream finished")

		return res, nil
	},
}
```
<img width="1115" alt="screen shot 2018-02-02 at 15 04 22" src="https://user-images.githubusercontent.com/10452377/35737012-609344f6-082a-11e8-90ef-dee26f8fbbb9.png">

**Comment by fd** [comment]
Are you running against the latest version of the graphql package? I believe these issues are fixed now.

**Comment by leebenson** [comment]
@Kliton - can you confirm if this has been resolved?
