### ISSUE TITLE
Return error array from a field resolver

### ISSUE THREAD

**Issue by SciGno** [graphql-go/graphql#281]
Having the following mutation query:

```
mutation {
  register(
    email: [
      {email: "username1.domain.com"},
      {email: "username2@domain.com"}
    ]
}
```
I would like to send the following response:

```
{
  "data": {
    "register": null
  },
  "errors": [
    {
      "message": "invalid_format: username1.domain.com",
      "locations": []
    },
    {
      "message": "email_exists: username2@domain.com",
      "locations": []
    }
  ]
}
```
I assume it's impossible since the Resolve field is defined as:
```
type FieldResolveFn func(p ResolveParams) (interface{}, error)
```
I don't understand why the implementation returns an error array but does not allow me to do so?
Am I missing something?

Thanks in advance for any help or guidance.

**Comment by SciGno** [comment]
Any advice or workaround on how I can accomplish this?

**Comment by djmcgreal** [comment]
Hi,
Whilst I originally 👍 on this, the specification states that there can be at most one error per field, http://facebook.github.io/graphql/October2016/#sec-Errors-and-Non-Nullability.
I do find this decision a little odd and the alternative (introducing a wrapper error that clients need to know how to parse), isn't super appealing, but is probably what we're left with.
Dan.

**Comment by SciGno** [comment]
@djmcgreal what I get from that section of the specs is that they only address the error from the perspective of the requested field and not from the perspective of the resolver of the field.  If InputTypes are allowed then there should be a way for the resolver to send back an error that points to the exact location/locations in the argument/s in the request.  But like you said, that's what we are left with :).

The reason for my request is that one might have some mutations that can have many arguments and InputTypes.  By allowing multiple errors, we can implement a more complex mutation operation and return more specific errors pointing to those arguments.

This is my workaround for now.  I made some modifications to graphql-go/handler/handler.go.  
In the ContextHandler function, I added the code bellow.

```go
// contextErrors will be assigned the errors
var contextErrors gqlerrors.FormattedErrors

// append a function in the context that can be called to pass the errors
// to be assigned to contextErrors variable
ctx = context.WithValue(ctx, ContextKey(ErrorsContextKey), func(e gqlerrors.FormattedErrors) { contextErrors = e })

// execute graphql query
...

// process the contextErrors array and append it to result.Errors
if len(contextErrors) > 0 {
   if result.HasErrors() { // append the errors to exsisting errors
      for _, v := range contextErrors {
         result.Errors = append(result.Errors, v)
      }
    } else {
     result.Errors = contextErrors
     }
}
```

Then this is how I would send my messages.  I have struct with some methods to publish the errors.

```go
arr := gqlerrors.FormattedErrors{}

for _, v := range c.gqlErrors {
	tmp := gqlerrors.FormattedError{
		Message:   v.Message,
		Locations: v.locations.Get(),
	}
	arr = append(arr, tmp)
}

if len(arr) > 0 {
	errorsFunc := ctx.Value(handler.ContextKey(handler.ErrorsContextKey)).(func(e gqlerrors.FormattedErrors))
	errorsFunc(arr)
}
```
Leandro
