### ISSUE TITLE
Input context to resolver

### ISSUE THREAD

**Issue by tanphamhaiduong** [graphql-go/graphql#333]
Hi, I have problem that i do not know how to pass context to each resolver and i cannot find it on google. Could anybody help me ?

**Comment by glaslos** [comment]
Did you see this? https://github.com/graphql-go/graphql/blob/master/examples/context/main.go

**Comment by tanphamhaiduong** [comment]
@glaslos thanks for your information, i found solution, because i use https://github.com/graphql-go/handler so i wrapped handler with middleware to add context to it

**Comment by chris-ramon** [comment]
thanks a lot for answering @glaslos!, really appreciate it, since it was resolved closing this one, cheers!
