### ISSUE TITLE
how to return other field?

### ISSUE THREAD

**Issue by 503945930** [graphql-go/graphql#339]
how to get  this struct?
```
{
  "data": {
    "user": {
      "count": 1,
         "rows": [
        {
          "id": "32436880-25bb-11e7-8306-53622de10340",
          "displayName": "gass123gggggg",
          "mobile": "18575740461",
          "wechat": {
            "id": "a5b727a0-25bd-11e7-a904-ab5ece618bae",
            "nickName": "2333333"
          }
        }
      ]
    }
  },
  "code": 200,
  "status": "OK"
  "server_time": 1496727468000
}
```

**Comment by gabrielruiu** [comment]
Im not one of the devs but I believe that the JSON responses from a GraphQL interface (regardless what library implements it) are restricted to having only the two root fields `data` and `errors`. There is nothing in the spec mentioning that other fields can be added beside them.

See [here](https://graphql.org/learn/serving-over-http/#response)

So you will have to deliver the `code`, `status` and `server_time` within the `data` object.

**Comment by 503945930** [comment]
ok
