### ISSUE TITLE
"Runtime error: Nil pointer reference" while serializing null string pointer

### ISSUE THREAD

**Issue by dreamer-89** [graphql-go/graphql#365]
Do we need to add null pointer handling in graphql/scalers.go ?

func coerceString(value interface{}) interface{} {
	if v, ok := value.(*string); ok {
		return *v
	}
	return fmt.Sprintf("%v", value)
}

**Comment by chris-ramon** [comment]
Thanks a lot for filing the issue @dreamer-89 — this was addressed via: https://github.com/graphql-go/graphql/pull/369, so closing the issue.
