### ISSUE TITLE
Enum inside a InputObject

### ISSUE THREAD

**Issue by glaslos** [graphql-go/graphql#382]
I have an issue with using a Enum type in an InputObject type:
```golang
var filterInputType = graphql.NewInputObject(graphql.InputObjectConfig{
	Name: "filterInput",
	Fields: graphql.InputObjectConfigFieldMap{
		"status": &graphql.InputObjectFieldConfig{
			Type:        statusEnum,
			Description: "status enum",
		},
	},
})
```
```golang
var statusEnum = graphql.NewEnum(graphql.EnumConfig{
	Name: "Status Enum",
	Values: graphql.EnumValueConfigMap{
		"PENDING": &graphql.EnumValueConfig{
			Value: 0,
		},
		"DONE": &graphql.EnumValueConfig{
			Value: 1,
		},
	},
})
```
Compiling this works but the Schema in the playground complains: `Uncaught Error: Invalid or incomplete schema, unknown type: . Ensure that a full introspection query is used in order to build a client schema.`

**Comment by bhoriuchi** [comment]
I ran into this issue as well. I got around it by adding the type to the schema config

```golang

schemaConfig := graphql.SchemaConfig{
    Query:    rootQuery,
    Mutation: rootMutation,
    Types: []graphql.Type{
        statusEnum,
        filterInputType,
    },
}
```

**Comment by evulse** [comment]
I thought this was odd as I'm using Enum's the same way as you without issues, however noticed you have a space in your name "Status Enum", I can confirm this causes the issue you mentioned if I apply a space to any of my usages. If you remove it and call it "StatusEnum" you should be fine.

**Comment by glaslos** [comment]
Thanks :woman_facepalming: your response should have been the error message...
