### ISSUE TITLE
Setting headers based on response body from GraphQL POST request?

### ISSUE THREAD

**Issue by debnath** [graphql-go/graphql#391]
Hi guys. I would like to set a response header depending on the contents of the response body from GraphQL. Specifically, I want to set a Cache-Control max-age value depending on the contents of the response body.
 
The only way I can think of to do this is to write a middleware that calls the graphql handler,  parses the entire response body, looks for a specific field, and then adds the header.  This gets complicated however as the response structure can be different depending on how the API consumer structures the request query (e.g. if they added aliases)... so any parsing logic gets messy fast. 

Is there a better way to do this?  Ideally I could set an request-level context variable (an Echo context in my case) from the actual GraphQL resolver function, but I don't have that request context available on the schema definition level.  The alternative outside of that is to set some global package variable, but that will likely lead to race conditions as I am expecting a high volume of traffic.

Any suggestions for how I can solve this? I am happy to dig into and modify the graphql-go internals if necessary, but any hints would be appreciated.

**Comment by debnath** [comment]
Please disregard: I can see now that graphql-go actually does have a way to access context from schema definition:  https://github.com/graphql-go/graphql/blob/master/examples/modify-context/main.go

**Comment by chris-ramon** [comment]
> Please disregard: I can see now that graphql-go actually does have a way to access context from schema definition: https://github.com/graphql-go/graphql/blob/master/examples/modify-context/main.go

Hi @debnath!, thanks for using the lib and reaching us for a question.

That's correct, for your use case, you can leverage the [`graphql.ResolveParams.Info.RootValue`](https://github.com/graphql-go/graphql/blob/master/examples/modify-context/main.go#L23) which is mutable and available from top-down in your resolvers tree.
