### ISSUE TITLE
Supporting Path on ResolveInfo

### ISSUE THREAD

**Issue by quangbuule** [graphql-go/graphql#404]
Hi,

I saw a line in graphql-js (of Facebook) that support `Path` in `ResolveInfo`. I am not sure if we should support this? I would love to do pull request for this.

https://github.com/graphql/graphql-js/blob/c82ff68f52722c20f10da69c9e50a030a1f218ae/src/type/definition.js#L494

Thanks a lot!

**Comment by chris-ramon** [comment]
Hi @quangbuule, thanks for reaching us for an feature request, which was addressed via: https://github.com/graphql-go/graphql/pull/403

Closing this one via: https://github.com/graphql-go/graphql/pull/403
