### ISSUE TITLE
BindFields doesn't handle time.Time type

### ISSUE THREAD

**Issue by limoli** [graphql-go/graphql#415]
I detected a bug using `BindFields` utility. @jekiapp 
This is the panic error trying to bind fields of a normal structure:
`panic: reflect.Value.Interface: cannot return value obtained from unexported field or method`

**Structure**
```go
type User struct {
	Id          int64         `gorm:"primary_key" json:"id"`
	Sid         string        `json:"sid"`
	Role        UserRole      `json:"role"`
	Status      UserStatus    `json:"status"`
	Firstname   string        `json:"firstname"`
	Lastname    string        `json:"lastname"`
	Birthdate   time.Time     `gorm:"type:date" json:"birthdate"`
	...
}
```

It fails exactly on the reflection of Birthdate field, indeed when there is the loop of fields, the Birthdate field is iterated as:
```go
// line 27 @ util.go
for i := 0; i < t.NumField(); i++ {
	field := t.Field(i)

	tag := extractTag(field.Tag)
	if tag == "-" {
		continue
	}

	fieldType := field.Type

	if fieldType.Kind() == reflect.Ptr {
		fieldType = fieldType.Elem()
	}

	var graphType Output
	if fieldType.Kind() == reflect.Struct {
		// PANIC ON THE RECURSION
		structFields := BindFields(v.Field(i).Interface())

		if tag == "" {
			fields = appendFields(fields, structFields)
			continue
		} else {
			graphType = NewObject(ObjectConfig{
				Name:   tag,
				Fields: structFields,
			})
		}
	}
```

field.Name gets the following values for each iteration:
- Id
- Sid
- Role
- Status
- Firstname
- Lastname
- Birthdate
- wall (field of time.Time struct)
- ext (field of time.Time struct)
- loc (field of time.Time struct)
- **PANIC ERROR**

The panic error is cause by `v.Field(i).Interface()` : 
```go
// Interface returns v's current value as an interface{}.
// It is equivalent to:
//	var i interface{} = (v's underlying value)
// It panics if the Value was obtained by accessing
// unexported struct fields.
func (v Value) Interface() (i interface{}) {
	return valueInterface(v, true)
}
```

**Comment by jekiapp** [comment]
I'll try to create a PR to fix this bug. For now you can do something like this, Let's say you had this struct, notice the `json` tag `-`
```
     type User struct {
        Birthdate time.Time `json:"-"`
     }
```

Let's say you create fields with `BindFields()` then you can manually add the `birthdate` field like below snippet:
```
       fields := graphql.BindFields()
	obj := graphql.NewObject(graphql.ObjectConfig{
		Fields:fields,
	})
	obj.AddFieldConfig("birthdate",&graphql.Field{
		Name:"Birthdate",
		Resolve: func(p graphql.ResolveParams) (interface{}, error) {
			user := p.Source.(User)
			// do some formatting for user.Birthdate
			return formattedBirthdate,nil
		},
	})
```

**Comment by taylorhoward92** [comment]
What is the underlying cause of the panic?

I'm using my struct type definition to define a GraphQL object but also using it to unmarshal JSON messages incoming to my application through other means outside of GraphQL. This means that I can't use the work around of setting the `json` tag as `-` because I'd miss out on that field when unmarshaling the JSON messages.

**Comment by mylxsw** [comment]
I have the same problem with `time.Time`

**Comment by jekiapp** [comment]
The way I solve this is to treat any implementor of interface `encoding.TextMarshaler` as string. this include `time.Time` so you should be able to use it as your field type

**Comment by chris-ramon** [comment]
closed via: https://github.com/graphql-go/graphql/pull/503
