### ISSUE TITLE
How I get...

### ISSUE THREAD

**Issue by robindata-gmbh** [graphql-go/graphql#416]
Hi,

how I get http.ResponseWriter and *http.Request into 
`Resolve: func(p graphql.ResolveParams) (interface{}, error) {` ?

**Comment by robindata-gmbh** [comment]
I implement a JWT-Token middelware and this process need that one http.request.

**Comment by sfriedel** [comment]
Just have a look at the example, specifically [line 50](https://github.com/graphql-go/graphql/blob/master/examples/context/main.go#L50) and [line 36](https://github.com/graphql-go/graphql/blob/master/examples/context/main.go#L36).

Even though the example uses the context to pass down a user object, you can use the context in the same way to pass any object you want, including the `http.Request`.

**Comment by robindata-gmbh** [comment]
context.Context consign a value but not a struct/object.

**Comment by robindata-gmbh** [comment]
`
result := graphql.Do(graphql.Params{
		Schema:        schema,
		RequestString: string(query),
		Context:       context.WithValue(context.Background(), "httprequest", r),
	})
`


`
r := p.Context.Value("httprequest").(*http.Request)
`

is working... Thx!!!
