### ISSUE TITLE
POST Example

### ISSUE THREAD

**Issue by robindata-gmbh** [graphql-go/graphql#420]
How I can send a request by POST-Method with the following shema?

Under examples can I find only GET-Requests!

```
{ 
  "query" :  "..." , 
  "operation" :  "..." , 
  "variables" :  {  "myVariable" :  "somevalue" ,  . . .  } 
}
```

with : 

```
curl -XPOST http://localhost:5000/xql -H 'Content-Type: application/json' -d \
'{
  "query": "mutation tokenAuth($email:String, $password:String)",
  "variables": "{\"email\": \"emai@domain.com\", \"password\": \"password\"}"
}'
```

currently have I a error: "Syntax Error GraphQL request (2:3) Expected Name, found String \"query\...."

What's my problem? :)

**Comment by atombender** [comment]
You have to unmarshal it yourself, as apparently this library doesn't have that:

```go
type postData struct {
	Query     string                 `json:"query"`
	Operation string                 `json:"operation"`
	Variables map[string]interface{} `json:"variables"`
}

// ...

mux.Post("/graphql", func(w http.ResponseWriter, req *http.Request) {
  var p postData
  if err := json.NewDecoder(req.Body).Decode(&p); err != nil {
    w.WriteHeader(400)
    return
  }
  result := graphql.Do(graphql.Params{
		Context:        req.Context(),
		Schema:         schema,
		RequestString:  p.Query,
		VariableValues: p.Variables,
		OperationName:  p.Operation,
	})
	if err := json.NewEncoder(w).Encode(result); err != nil {
		srv.logger.Debugf("could not write result to response: %s", err)
	}
})
```

**Comment by acgreek** [comment]
what is the mux variable? Google search for 'golang mux' returns 'gorrilla mux' as a likely candidate, thought the router returned from mux.NewRouter() doesn't have a Post method.

**Comment by atombender** [comment]
I use [Chi](https://github.com/go-chi/chi), but you can use the Go HTTP server.

**Comment by maapteh** [comment]
Weird to see only Get examples. All implementations are Post (security) . So first thing i did was updating playground to latest https://github.com/graphql/graphql-playground/blob/master/packages/graphql-playground-html/minimal.html and then found the above issue and thought ...
