### ISSUE TITLE
Potential data race

### ISSUE THREAD

**Issue by BurtonQin** [graphql-go/graphql#429]
I found a potential data race between the following two instructions:
1. https://github.com/graphql-go/graphql/blob/21fe71deb5864761ea88e1dbc98e973964c9127c/executor.go#L57
2. https://github.com/graphql-go/graphql/blob/21fe71deb5864761ea88e1dbc98e973964c9127c/executor.go#L70

**Comment by songlh** [comment]
Any update? By reading the code, this is definitely a data race.
