### ISSUE TITLE
Object type argument

### ISSUE THREAD

**Issue by asaf** [graphql-go/graphql#508]
Hey,

I have a root query field that i'm trying to query by nested argument such:

```graphql
{
  User(name: {givenName: "Asaf"}) {
    displayName
  }
}
```

This is how the query definition looks like:

```go
queryFields["User"] = &graphql.Field{
		Name: "User",
		Type: UserObject,
		Args: graphql.FieldConfigArgument{
			"name": &graphql.ArgumentConfig{
				Type: graphql.NewObject(graphql.ObjectConfig{
					Name: "name",
					Fields: graphql.Fields{
						"givenName": &graphql.Field{
							Type: graphql.String,
						},
					},
				}),
			},
		},
		Resolve: func(p graphql.ResolveParams) (interface{}, error) {
                    // p.Args is empty!
                    fmt.Println(p.Args)
                 },
	}
```

Query passes validation but `p.Args` in resolver is empty,

I dig into code a bit and this is because the method:
`func valueFromAST(valueAST ast.Value, ttype Input, variables map[string]interface{}) interface{} {` in `values.go` has a switch case of `*InputObject`

But the value being passed by AST(ttype var) is `*Object` rather `*InputObject`

(btw if I change `*InputObject` to `*Object` it parses it ok)

Would appreciate some advice here,

Thanks,

Asaf.

**Comment by sfriedel** [comment]
@asaf In case you haven't figured this out already, I think the problem is that your `name` type is a `Object` instead of `InputObject`.

Try replacing
```go
"name": &graphql.ArgumentConfig{
    Type: graphql.NewObject(graphql.ObjectConfig{
        Name: "name",
        Fields: graphql.Fields{
            "givenName": &graphql.Field{
                Type: graphql.String,
            },
        },
    }),
},
```

with this

```go
"name": &graphql.ArgumentConfig{
    Type: graphql.NewInputObject(graphql.InputObjectConfig{
        Name: "name",
        Fields: graphql.InputObjectConfigFieldMap{
            "givenName": &graphql.InputObjectFieldConfig{
                Type: graphql.String,
            },
        },
    }),
},
```

**Comment by asaf** [comment]
@sfriedel yea managed, thanks, since some params (such Type/Fields) are `interfaces{}` I had 
to debug the code in order to figure exactly what type object needs to be constructed.

I wonder why we can't just re-use the object defined for query field (or at least its fields) for the input args, since we can't pass `Fields` (rather required to pass `InputObjectConfigFieldMap` and `InputObjectFieldConfig`) so there's no way to re-use fields rather the need to re-build them from scratch, feels redundant to me.

Thanks!

**Comment by sfriedel** [comment]
> I wonder why we can't just re-use the object defined for query field (or at least its fields) for the input args, since we can't pass Fields (rather required to pass InputObjectConfigFieldMap and InputObjectFieldConfig) so there's no way to re-use fields rather the need to re-build them from scratch, feels redundant to me.

I believe the reason for this is that not all fields that can be used in a `Object` type are allowed to be used on an `InputObject` (e.g. `Union` and `Interface` types). Not sure if the library actually validates this though.

**Comment by asaf** [comment]
@sfriedel yea, this library follows [graphql-js](https://github.com/graphql/graphql-js) design and spec dictates different objects for in / out because of references to [unions and interfaces](https://graphql.github.io/graphql-spec/April2016/#sec-Input-Objects)

**Comment by asaf** [comment]
@sfriedel yea, this library follows [graphql-js](https://github.com/graphql/graphql-js) design and spec dictates different objects for in / out because of references to [unions and interfaces](https://graphql.github.io/graphql-spec/April2016/#sec-Input-Objects)
