### ISSUE TITLE
New Home -> github.com/graphql-go/graphql

### ISSUE THREAD

**Issue by chris-ramon** [graphql-go/graphql#52]
When I started `graphql-go/graphql` formerly `chris-ramon/graphql-go`, my vision was to release a GraphQL implementation in Go ... so eventually I could end-up using it within Go programs I would like to write, that vision today is share with many awesome people from the Go community, so that's why I've transferred the repository to the organization `github.com/graphql-go`, which will maintain & release GraphQL related libs.

So thanks again to all the people that is making this possible! :star2: - Looking forward to release the Alpha version and hopefully very soon a prod-ready one! :rocket: 

Happy GraphQL Go coding! :smile:

**Comment by EmergentBehavior** [comment]
:+1:  * :100:

**Comment by F21** [comment]
Good stuff! I wonder if @sogko would be interested in moving the `graphql-relay-go` project to `graphql-go` as well.

**Comment by sogko** [comment]
This is great! I've been really excited for this! 👍🏻

@F21 Yeap, thats part of the plan, to consolidate core `graphql-go` components within the ecosystem into the organization's repo.

I have moved the following repos into `graphql-go`:
- [`graphql-relay-go`](https://github.com/graphql-go/graphql-relay-go)
- [`graphql-go-handler`](https://github.com/sogko/graphql-go-handler)
- [`golang-graphql-playground`](https://github.com/graphql-go/golang-graphql-playground)

There are other little example projects that I've written. They are not core components but could possibly go into `graphql-go`, let me know if you guys think it make sense to move them. I would love to encourage the community to pick it up and maintain it together if the examples prove helpful to them.
- https://github.com/sogko/golang-relay-starter-kit 
- https://github.com/sogko/todomvc-relay-go

For example, `golang-relay-starter-kit`'s JS equivalent [`relay-starter-kit`](https://github.com/relayjs/relay-starter-kit) is in [`github.com/relayjs`](https://github.com/relayjs), not [`github.com/graphql`](https://github.com/graphql)

Let me know what you guys think.

Also, anyone is welcome to beat me to the punch and send PRs for any of the other projects to fix broken import paths, etc 👍🏻

Cheers guys! Let's do this!

**Comment by thanhliem89dn** [comment]
really cool :+1:

**Comment by sogko** [comment]
Opps, one more thing that I forgot to mention.

Regarding the newly-transferred repos, I would like to hear feedback for their repo names and package names.

Here's my initial suggestions:

| Repository name                                                                                                                            | Package name              |
|----------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------|
| [`github.com/graphql-go/graphql-relay-go`](https://github.com/graphql-go/graphql-relay-go) -> `github.com/graphql-go/relay`                        | `gqlrelay` -> `relay`     |
| [`github.com/graphql-go/graphql-go-handler`](https://github.com/sogko/graphql-go-handler) -> `github.com/graphql-go/handler`                       | `gqlhandler` -> `handler` |
| [`github.com/graphql-go/golang-graphql-playground`](https://github.com/graphql-go/golang-graphql-playground) -> `github.com/graphql-go/playground` | -                         |

Welcome any feedback 👍🏻

**Comment by F21** [comment]
@sogko That sounds good to me!

**Comment by pyros2097** [comment]
@sogko all good to me

**Comment by christianpv** [comment]
@sogko LGTM :+1:

**Comment by sogko** [comment]
Updates:
I've renamed the repos and packages as mentioned above, and updated them with the new import paths.

**Comment by chris-ramon** [comment]
> Updates:
> I've renamed the repos and packages as mentioned above, and updated them with the new import paths.

Great! thanks for updates, I def agree on following go pkg short naming convention 
across all `graphql-go` libs.
