### ISSUE TITLE
Going out of life?

### ISSUE THREAD

**Issue by schaze** [graphql-go/graphql#527]
How are the future plans for graphql-go?
I can see there is is only very "slow" progress and a lot of issues are unanswered. 
Is this still active or nearing end of life?

To be clear: This is in no way complaining - I am merely looking for a future proof graphql library in go and want to be sure it will continue to get some love.
I am in need of a runtime design schema creation library as I have the need to dynamically create parts of the schema. This does not work with all the "schema" first ones (with codegenerators and what not). However I have not found any alternative than to this one.

**Comment by chris-ramon** [comment]
Hi @schaze, thanks for raising up this conversation:

> How are the future plans for graphql-go?

FMHO the future plans for graphql-go continues to be as the initial vision to have a Go's GraphQL implementation that follows the oficial reference implementation: [graphql-js](https://github.com/graphql/graphql-js).

> I can see there is is only very "slow" progress and a lot of issues are unanswered.

We have many awesome contributors that were improving the library along the way, hopefully we can catch-up closing more issues and merging PRs.

> Is this still active or nearing end of life?

graphql-go is definitely an active project, I personally have being using it for production for many years now, and I read of many companies that are as well.

> To be clear: This is in no way complaining - I am merely looking for a future proof graphql library in go and want to be sure it will continue to get some love.

Glad to know you're interested in using/continue-to-use graphql-go

> I am in need of a runtime design schema creation library as I have the need to dynamically create parts of the schema. This does not work with all the "schema" first ones (with codegenerators and what not). However I have not found any alternative than to this one.

Sounds like a neat runtime design of schemas, it would be great external library that could work together with graphql-go and we could list it in the [third party libraries section](https://github.com/graphql-go/graphql#third-party-libraries).

**Comment by schaze** [comment]
Thanks for taking the time to answer my question in so much detail! I am glad to hear the lib is healthy.

I don't think my project will produce a library that is usable on its own - however depending how it plays out I will probably post some interesting implementation examples.

**Comment by schaze** [comment]
Should I close this?

**Comment by chris-ramon** [comment]
> Should I close this?

Yes, thanks @schaze 👍
