### ISSUE TITLE
Cannot implement go routines in graphql-go

### ISSUE THREAD

**Issue by vishnutm** [graphql-go/graphql#544]
Hey @chris-ramon, 

Currently, try to perform Nearby function in a concurrent manner.  

**My Resolver function**

`func GetNearbyUser() *graphql.Field {
	return &graphql.Field{
		Type: graphql.NewList(types.NearbyType),
		Args: graphql.FieldConfigArgument{

			"latitude": &graphql.ArgumentConfig{
				Type: graphql.NewNonNull(graphql.Float),
			},

			"longitude": &graphql.ArgumentConfig{
				Type: graphql.NewNonNull(graphql.Float),
			},

			"collection": &graphql.ArgumentConfig{
				Type: graphql.NewNonNull(graphql.String),
			},

			"radius": &graphql.ArgumentConfig{
				Type:         graphql.Float,
				DefaultValue: 2000.00,
			},
		},

		Resolve: func(params graphql.ResolveParams) (interface{}, error) {

			ch := make(chan []types.NearbyLocation)

			go func() {
				var Lat = params.Args["latitude"].(float64)
				var Long = params.Args["longitude"].(float64)
				var radius = params.Args["radius"].(float64)
				var collection = params.Args["collection"].(string)
				response, _ := tile38.Nearby(collection, Lat, Long, radius)
				ch <- response
			}()

			return func() interface{} {

				return <-ch
			}, nil

			// if err != nil {
			// 	//log.Println(err)
			// 	return nil, err
			// }
			//return response, nil
		},
	}
}`

My Nearby function

![Screenshot from 2020-05-16 23-11-24](https://user-images.githubusercontent.com/30982642/82126459-9c518e80-97ca-11ea-8d9c-182d064e67d1.png)

when trying to call the nearby function in postman

**RESULT :**

`query {nearbyUser(collection:"driver",latitude:8.55652,longitude:76.872894,radius:2000){latitude,longitude,id}}`

![Screenshot from 2020-05-16 23-14-40](https://user-images.githubusercontent.com/30982642/82126559-37e2ff00-97cb-11ea-99d0-056fb3e6f9da.png)

**Addition Information:**
Adding the current struct types and objects
`type UserLocation struct {
	ID       string  `json:"id"`
	Collection string  `json:"collection"`
	Lat      float64 `json:"latitude"`
	Long     float64 `json:"longitude"`
}

// GetLocation : The structure for querying user location response [query:user]
type GetLocation struct {
	LocationType string  `json:"type"`
	Latitude     float64 `json:"latitude"`
	Longitude    float64 `json:"longitude"`
}

// NearbyLocation : The structure for querying nearby users response [query:nearbyUser]
type NearbyLocation struct {
	ID        string  `json:"id"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

// UserType is the GraphQL schema for the response of creating user.
var UserType = graphql.NewObject(graphql.ObjectConfig{
	Name: "UserLocation",
	Fields: graphql.Fields{

		"id": &graphql.Field{
			Type: graphql.String,
		},
		"collection": &graphql.Field{
			Type: graphql.String,
		},
		"latitude": &graphql.Field{
			Type: graphql.Float,
		},

		"longitude": &graphql.Field{
			Type: graphql.Float,
		},
	},
})

// GetResponse is the GraphQL schema for the response of tile38 GET query
var GetResponse = graphql.NewObject(graphql.ObjectConfig{
	Name: "GetLocation",
	Fields: graphql.Fields{

		"type": &graphql.Field{
			Type: graphql.String,
		},
		"latitude": &graphql.Field{
			Type: graphql.Float,
		},
		"longitude": &graphql.Field{
			Type: graphql.Float,
		},
	},
})

// NearbyType is the Graphql schema the response of tile38 NEARBY query
var NearbyType = graphql.NewObject(graphql.ObjectConfig{

	Name: "NearbyLocation",
	Fields: graphql.Fields{

		"id": &graphql.Field{
			Type: graphql.String,
		},
		"latitude": &graphql.Field{
			Type: graphql.Float,
		},
		"longitude": &graphql.Field{
			Type: graphql.Float,
		},
	},
})`

I also attach main.go file below

`func main() {

	// Set the file name of the configurations file
	viper.SetConfigName("config")
	// Set the path to look for the configurations file
	viper.AddConfigPath("./config")

	viper.SetConfigType("yml")
	// Enable VIPER to read Environment Variables
	viper.AutomaticEnv()

	var configuration c.Configurations

	if err := viper.ReadInConfig(); err != nil {
		fmt.Printf("Error reading config file, %s", err)
	}

	err := viper.Unmarshal(&configuration)

	if err != nil {
		fmt.Printf("Unable to decode into struct, %v", err)
	}

	router := mux.NewRouter().StrictSlash(true)
	//log.Printf(" Server started on http://localhost:8080/\n")

	// GraphQl schema configuration
	schemaConfig := graphql.SchemaConfig{
		Query: graphql.NewObject(graphql.ObjectConfig{
			Name:   "RootQuery",
			Fields: queries.GetRootFields(),
		}),
		Mutation: graphql.NewObject(graphql.ObjectConfig{
			Name:   "RootMutation",
			Fields: mutations.GetRootFields(),
		}),
	}
	schema, err := graphql.NewSchema(schemaConfig)

	if err != nil {
		log.Fatalf("Failed to create new schema, error: %v", err)
	}

	httpHandler := handler.New(&handler.Config{
		Schema: &schema,
		Pretty: true,
	})

	router.Handle("/v1", httpHandler)
	router.HandleFunc("/", homeLink)

	l := log.New(os.Stdout, "product-api", log.LstdFlags)
	if _, err := c.Client.Ping().Result(); err != nil {

		e := Error.Wrap(err, ",Redis server down,", http.StatusBadGateway)

		log.Println(e)
	}

	s := &http.Server{

		Addr:         ":" + configuration.Server.Port,
		Handler:      router,
		IdleTimeout:  120 * time.Second,
		ReadTimeout:  1 * time.Second,
		WriteTimeout: 10 * time.Second,
		ErrorLog:     l,
	}

	go func() {

		log.Println("Server started on the port 8080")
		err := s.ListenAndServe()
		if err != nil {
			l.Printf("Error starting server: %s \n ", err)
			os.Exit(1)
		}

	}()

	// trap sigterm or interupt and gracefully shutdown the server
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)
	signal.Notify(c, os.Kill)

	// Block until a signal is received.
	sig := <-c
	log.Println("Got the signal", sig)

	// gracefully shutdown the server, waiting max 30 seconds for current operations to complete
	ctx, _ := context.WithTimeout(context.Background(), 30*time.Second)
	s.Shutdown(ctx)

}`

Waiting for valuble feedback.

**Comment by Fontinalis** [comment]
Hey @vishnutm,

If you check the [example for the concurrent resolvers](https://github.com/graphql-go/graphql/blob/116f19d099aa03ceb19da9b5a0466db4c8d8b5f3/examples/concurrent-resolvers/main.go#L61), you can see that the issue is that your resolver returns a `func() interface{}`, but the concurrent resolvers has to be `func() (interface{}, error)` as your error highlighted.

So if you change your 
```
return func() (interface{}, error) {
   return <-ch, nil
}, nil
```

**Comment by vishnutm** [comment]
@Fontinalis, Thanks mate it's worked
