### ISSUE TITLE
[question] how to get argument in nested quey

### ISSUE THREAD

**Issue by cacing69** [graphql-go/graphql#556]
according to graphql pagination example, i want to create a simmiliar query like this https://graphql.org/learn/pagination/

![image](https://user-images.githubusercontent.com/36250619/87872831-1fb77800-c9e6-11ea-8025-b3ffcd28cfb8.png)

i can get username arg on top level but, how to get arg **last** in **log**  query

**Comment by cacing69** [comment]
![image](https://user-images.githubusercontent.com/36250619/87935977-42b45b80-cabc-11ea-9f62-4e4eaddd43aa.png)
for temporary i used this method to get args if someone know how to get with a simple ways, pls tell me.

on next i will make this recursive where they will get all args deeper
![image](https://user-images.githubusercontent.com/36250619/87936099-77281780-cabc-11ea-8aac-c1f6f23bc1fc.png)
![image](https://user-images.githubusercontent.com/36250619/87936113-7ee7bc00-cabc-11ea-8726-d04354ffa1c6.png)

**Comment by bhoriuchi** [comment]
I wrote a library that will make working with and defining custom directives easier https://github.com/bhoriuchi/graphql-go-tools

The example shows how to define and use a directive. The args will be provided to the directive handler function as a map[string]interface{}

Other than that the only change to your workaround approach i would make is to define a recursive function in the event your argument is a complex type.
