### ISSUE TITLE
Testing against Go 1.5 in CI.

### ISSUE THREAD

**Issue by EmergentBehavior** [graphql-go/graphql#57]
I use Go 1.5 locally, but the Travis yaml only tests against Go 1.4. I recommend either replacing 1.4 with 1.5 or testing against both.

**Comment by sogko** [comment]
I'm using Go 1.5 locally as well.
(Specifically `go version go1.5.1 darwin/amd64`)
Would be nice to know what everyone else here is using on their machine.

We can definitely test both 1.4 and 1.5 to the CI, just to see how well the code stand against previous minor version of Go.

Related question: Going forward, what's our strategy for supporting versions of Go? 
It appears that Go releases a minor version (i.e. 1.4 -> 1.5) on a 6-month cycle, [somewhat](https://golang.org/doc/devel/release.html)
(Anyone know the official word on this?)

We can probably do: `current minor version + previous minor version`, for e.g. `1.5 & 1.4`, which seems reasonable enough.

Or even simply `current minor version`, for e.g. `1.5 only`

Other references:

> For instance, code that runs under Go 1.2 should be compatible with Go 1.2.1, Go 1.3, Go 1.4, etc., although not necessarily with Go 1.1 since it may use features added only in Go 1.2
https://golang.org/doc/go1compat

**Comment by EmergentBehavior** [comment]
I'd support the current and previous minor versions (e.g. 1.5.x and 1.4.x).

**Comment by pyros2097** [comment]
Yeah.. same thing here.. I use go 1.5

**Comment by Fugiman** [comment]
Current and previous minor versions sounds great, but it may be nice to also test against tip to see future issues before they occur, and report them to golang devs. If this proves to be too noisy, it could just be a manual thing that's done when a minor version is about to be released.

**Comment by christianpv** [comment]
@chris-ramon we can close this issue since we merge #245

**Comment by chris-ramon** [comment]
@christianpv good catch!, closing this one.
