### ISSUE TITLE
TODO: A simple mutation example

### ISSUE THREAD

**Issue by sogko** [graphql-go/graphql#60]
With PR #21 and PR #59, we now have two basic examples that would benefit new users:
- Basic `Hello World` (query)
- Basic http example

Several people had asked for a working example of a mutation query, using purely GraphQL, (i.e. without Relay).

Currently the only example floating around is written by @bbuck in his gist here; albeit using the old API:
https://gist.github.com/bbuck/74cb8446cdb49bf8ac22

Putting this out there to invite anyone to contribute! 👍🏻

Update:  For #46 , I've added a mutation example there to address the question. May not be the best example for introduce someone to mutations, though.

**Comment by sogko** [comment]
I've re-written @bbuck's original example here:

https://gist.github.com/sogko/e298f9d1401e0ad736c6

**Comment by sogko** [comment]
This is another version of the above example, but using `graphql-go/handler` to create a server that handles GraphQL HTTP requests. (This probably should be in `graphql-go/handler`)

https://gist.github.com/sogko/7debd336118e5e7c7f65

##### How to make GraphQL HTTP request using cUrl
 In `graphql-go-handler`, based on the GET/POST and the Content-Type header, it expects the input params differently.
 This behaviour was ported from `express-graphql`. 

So given the following query:

```graphql
mutation M {
  newTodo: createTodo(text: "This is a todo mutation example") {
	text
	done
  }
}
```
###### using GET
```bash
$ curl -g -GET 'http://localhost:8080/graphql?query=mutation+M{newTodo:createTodo(text:"This+is+a+todo+mutation+example"){text+done}}'
```

###### using POST + Content-Type: application/graphql
```bash
$ curl -XPOST http://localhost:8080/graphql -H 'Content-Type: application/graphql' -d 'mutation M { newTodo: createTodo(text: "This is a todo mutation example") { text done } }'
```

###### using POST + Content-Type: application/json
```bash
$ curl -XPOST http://localhost:8080/graphql -H 'Content-Type: application/json' -d '{"query": "mutation M { newTodo: createTodo(text: \"This is a todo mutation example\") { text done } }"}'
```

Any of the above would return the same output:
```json
 {
   "data": {
	   "newTodo": {
		 "done": false,
		 "text": "This is a todo mutation example"
	   }
   }
 }
```

**Comment by EmergentBehavior** [comment]
Thanks @sogko!

**Comment by EmergentBehavior** [comment]
Also helpful to note, if there are "optional" params that you don't send in the query you'll have an issue trying to convert `nil` to `string`. I found this to be a suitable workaround:

`optionalVal, _ := params.Args["optionalVal"].(string)`

Prevents panicking. If I'm correct, it will default optionVal to the nil for string.

**Comment by sogko** [comment]
Oops, thanks for catching that @EmergentBehavior 👍🏻

**Comment by Fontinalis** [comment]
Closing issue since an example was added in #189 and even got better in #190
