### ISSUE TITLE
How to read frontend error messages?

### ISSUE THREAD

**Issue by mpldr** [graphql-go/graphql#619]
Hello, my schema gives me this error:

```json
{
  "data": null,
  "errors": [
    {
      "message": "Unknown type \"__Type\".",
      "locations": [
        {
          "line": 20,
          "column": 24
        }
      ]
    },
    {
      "message": "Unknown type \"__InputValue\".",
      "locations": [
        {
          "line": 53,
          "column": 26
        }
      ]
    },
    {
      "message": "Unknown type \"__Type\".",
      "locations": [
        {
          "line": 60,
          "column": 23
        }
      ]
    }
  ]
}
```

My main point of confusion is on how to "use" this error message. What lines is that referring to? In what file? What on earth is __Type? Some hidden built-in?

Sorry if this sounds somewhat desperate… I am at this point about an hour into just trying random stuff hoping to fix it.

**Comment by halfnibble** [comment]
@mpldr  It would be helpful if you posted your request data and the relevant Go code.

Also, this is probably more suited for StackOverflow unless you have a particular bug to report. I recommend you create a StackOverflow question, link it here, and then close this GitHub issue.

**Comment by mpldr** [comment]
I think there was an issue with my scheme, which for some reason made it misbehave… writing pretty much the same out as a scheme and it worked fine again…
