### ISSUE TITLE
 IsTypeOfFn

### ISSUE THREAD

**Issue by bsr203** [graphql-go/graphql#63]
Hi,

What is the field `IsTypeOf` of type `Object` used for? I don't see it in spec or `graphql-js`. Please remove if it not needed.

thanks.
bsr

```
type Object struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	IsTypeOf    IsTypeOfFn

	typeConfig ObjectConfig
	fields     FieldDefinitionMap
	interfaces []*Interface
	// Interim alternative to throwing an error during schema definition at run-time
	err error
}
```

**Comment by EmergentBehavior** [comment]
Is definitely in `graphql-js`, see this test:

https://github.com/graphql/graphql-js/blob/a941554fc56d607fecebe2188a7ca8848835c2a8/src/execution/__tests__/abstract.js#L44-L52

**Comment by bsr203** [comment]
oops.. ya, I am not sure how I missed it in the search. We don't use it now, so may keep this open to track it ???

**Comment by sogko** [comment]
Thanks @EmergentBehavior for pulling that out from `graphql-js`.

For reference, here's the ported test: https://github.com/graphql-go/graphql/blob/d80cf866ac948f8c830e1ffcae691409df55a700/abstract_test.go#L27

To elaborate further on `IsTypeOf`, it's usually would be used to check for the type of the value at runtime.
More specifically, for abstract types (i.e. interfaces and unions).

So a typical use-case would be when you have the following schema (as defined in the `TestIsTypeOfUsedToResolveRuntimeTypeForInterface` test)

```
// `Pet` is an interface, with a `name` field
interface Pet {
  name: String
}
// `Dog` implements `Pet`
type Dog : Pet {
  name: String
  woofs: Boolean
}
// `Cat` implements `Pet`
type Cat : Pet {
  name: String
  meows: Boolean
}
type Query {
  pets: [Pet] // `pets` returns a list of `Pet` interface
}
```

So, given the following query:
```
query Q {
  pets {
    name
  }
}
```
The `Resolve` function for `pets` field may return list of values that are of a `Cat` type or a `Dog` type (or any other type that implements `Pet` interface).

 `IsTypeOf` function then will be executed at runtime to determine it's concrete type, i.e. if the value return is a `Cat` type or a `Dog` type.

Regarding it being on the spec, it is there but it's very subtle:
> The interface type should have some way of determining which object a given result corresponds to. Once it has done so, the result coercion of the interface is the same as the result coercion of the object.
- http://facebook.github.io/graphql/#sec-Interfaces

> The union type should have some way of determining which object a given result corresponds to. Once it has done so, the result coercion of the union is the same as the result coercion of the object.
- http://facebook.github.io/graphql/#sec-Unions

`IsTypeOf` is just one way of implementing that spec. 

Note that `IsTypeOf` is defined in the concrete types (i.e. in `graphql.ObjectConfig`)
You can also choose to define `ResolveType` function in the abstract types (see `graphql.InterfaceConfig` and `graphql.UnionConfig`).

So `graphql-js/graphql-go` provides two ways to satisfy the above specs.

Hope that make sense, cos it's past midnight here lol. Cheers!

**Comment by bsr203** [comment]
@sogko thanks you so much for your time explaining it. I did a code search and missed the the usage (it was few commits behind). Thanks again.
