### ISSUE TITLE
GQLFRParams

### ISSUE THREAD

**Issue by bsr203** [graphql-go/graphql#64]
After the major rewrite, please consider

GQLFRParams  -> ResolveParams / Params

there is also a TODO in there 

```
TODO: clean up GQLFRParams fields
```

please consider what to be done, if none, may remove it.

**Comment by pkieltyka** [comment]
That would be nice, I agree its already in the `graphql` package.

**Comment by sogko** [comment]
Updates: Addressed in #68

**Comment by sogko** [comment]
Resolved in #68.

Thanks guys!
Cheers!
