### ISSUE TITLE
is this project dead ?

### ISSUE THREAD

**Issue by yvz5** [graphql-go/graphql#703]
there are lots of pull request waiting for approval and open issues. is this project not maintained anymore ?

**Comment by chris-ramon** [comment]
Sure @yvz5 go ahead and send a PR, I'll give it a look when I get a chance and hopefully it could get merged.

**Comment by chris-ramon** [comment]
> There was actually this important PR that has never been merged for some reaon. [#475](https://github.com/graphql-go/graphql/pull/475)

Thank you for the heads-up @alimoli, I'll give it a look when I have a chance.
