### ISSUE TITLE
Missing types in API doc

### ISSUE THREAD

**Issue by bsr203** [graphql-go/graphql#72]
Scalar types are missing from Godoc so hard to know they exist. For example, `graphql.Int` , `graphql.String`, .

I guess the `var` decl in this page need comments.

https://github.com/graphql-go/graphql/blob/master/scalars.go

**Comment by sogko** [comment]
This is one huge area that we need to improve in (documenting exported identifiers).
Documentation for built-in types are definitely a great start.

There are definitely better official GraphQL documentation than before, that we could use for our documentation:
- For e.g: http://graphql.org/docs/api-reference-type-system/#graphqlint

Much definitely welcome any PRs for this. Any takers?

**Comment by bbuck** [comment]
I tossed in some one liners really quick in #83 to satisfy some of the `go vet` notices. There are quite a bit more and I'd be more than happy to help contribute with some cleanup (documentation, go vet complaint free, etc...).

**Comment by Fontinalis** [comment]
Closing issue, scalars now can be found here in godoc [https://godoc.org/github.com/graphql-go/graphql#pkg-variables](https://godoc.org/github.com/graphql-go/graphql#pkg-variables)
