### ISSUE TITLE
error response

### ISSUE THREAD

**Issue by bsr203** [graphql-go/graphql#74]
As per the spec, https://facebook.github.io/graphql/#sec-Errors , error is indicated by a field `errors` of non empty list in the response.

so I was returning something like from my field resolver

```
return &graphql.Result{Errors: gqlerrors.FormatErrors(err)}
```

but that didn't work.

it does further validation and output the message

```
Locations: [{Line: 1, Column: 302}]
Message: "Cannot return null for non-nullable field GroupConnection.pageInfo."
```

my intention is to add more details to the error in the `data` field.

so, how can I return an error from `Resolve` method which passes to the client?

**Comment by sogko** [comment]
Currently there isn't a way to return a custom error from field resolvers.

This is being considered in #44, i.e. to allow user to return an error from Resolve function) https://github.com/graphql-go/graphql/issues/44#issuecomment-153282268

For e.g.:
```go
    helloResolve := func(p graphql.ResolveParams) (interface{}, error) {
        ...
        if err != nil {
            return nil, err
        }
        return "world", nil
    }
```
You're welcome to add to the discussion there to keep it going 👍🏻 (PRs are also welcomed :))

**Comment by bsr203** [comment]
closing so we track it at #44
