### ISSUE TITLE
Fragments in client mutation output not considered equal to their schema definition

### ISSUE THREAD

**Issue by atrniv** [graphql-go/graphql#77]
I encountered the following bug while building an app using relay and graphql-go. The application performs a mutation and requests a fragment spread in the mutation response. However graphql-go does not return back the correct response.

Input:

```
mutation GameConfigSetMutation($input_0:GameConfigSetInput!){
  GameConfigSet(input:$input_0){
    clientMutationId, 
    ...__RelayQueryFragment6jzsg6r,
  }
} 
fragment __RelayQueryFragment6jzsg6r on GameConfigSetPayload{
  viewer{
    game{
      config{
        logo,
        name
      }
    },
    id
  }
}
```

Output:

```
{
  "data": {
    "GameConfigSet": {
      "clientMutationId": "0",
    }
  }
}
```

However if I send this query the response is correct
Input

```
mutation GameConfigSetMutation($input_0:GameConfigSetInput!){
  GameConfigSet(input:$input_0){
    clientMutationId, 
   viewer{
    game{
      config{
        logo,
        name
      }
    },
    id
  }
} 

```

Output

```
{
  "data": {
    "GameConfigSet": {
      "clientMutationId": "0",
      "viewer": {
        "game": {
          "config": {
            "logo": "/images/fb85305f-9047-11e5-8c20-80fa5b10a4a4",
            "name": "boo"
          }
        },
        "id": "Vmlld2VyOg=="
      }
    }
  }
}
```

I dug through the code and I found that graphql-go fails because it decided that the fragment should not be included because the type of the fragment does not match the type of the mutation payload. It does this check through an equality check in the file `executor.go` [here](https://github.com/graphql-go/graphql/blob/master/executor.go#L384-L390)

I've currently applied a fix by checking `conditionalType.GetName() == ttype.GetName()` if the basic equality check fails. Is this the correct way to fix this ? Why are both the objects different instances ?

**Comment by sogko** [comment]
Hi @atrniv 
Thanks for using `graphql-go` and `relay`. Seems like you're working on a cool game project  👍🏻

1. I might need more information to properly access this issue. Is it possible to share the schema definition, at least for GameConfigSet mutation and GameConfigSetPayload?
2. Do you observed that this only affects mutation? Can you help to verify that similar fragment spread for non-mutation query works?
3. I noticed that you might be using an older version of the package (We recently made a huge change #68  and `GetName()` is now `Name()`). 
Would you want to consider updating your packages?
(Warning: Theres a huge API change to the exported structs and methods)

Cheers!

**Comment by thalesfsp** [comment]
@sogko Should this issue be closed? It as more than 1 year without any updates. Cheers!

**Comment by Fontinalis** [comment]
I'm closing the issue due to inactivity.
