### ISSUE TITLE
 introspection query fails with missing subscriptionType

### ISSUE THREAD

**Issue by bsr203** [graphql-go/graphql#86]
Using introspection query gave following error
```
"Cannot query field \"subscriptionType\" on \"__Schema\"."
```

This is due to the recent upgrade to graphql with support for subscription.
https://github.com/graphql/graphql-js/pull/189/files#diff-4ac20bee447bf30479babc3b266c5145R54

we may need to handle it here
https://github.com/graphql-go/graphql/blob/master/introspection.go#L269

**Comment by bsr203** [comment]
https://github.com/graphql-go/graphql/pull/87

**Comment by chris-ramon** [comment]
Thanks for initially suggesting  partial `subscriptionType` support within introspection @bsr203, it's been added on #100, related conversation [here](https://github.com/graphql-go/graphql/pull/100/files#r49266565).

**Comment by bsr203** [comment]
thanks chris
